#spring.application.name=lec20
server.port=8085

spring.datasource.generate-unique-name=false
#spring.datasource.name=tacocloud

spring.thymeleaf.cache=false
#spring.devtools.restart.enabled=false

#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

#spring.datasource.url=jdbc:mysql://localhost:3306/tacocloud?servertimezone=UTC&characterEncoding=UTF-8
#spring.datasource.username=root
#spring.datasource.password=piging1221!

MongoDB properties
#spring.mongodb.uri=mongodb+srv://atlasuser:taco1234@cluster0.q0wpkss.mongodb.net/tacoclouddb
spring.mongodb.uri=mongodb+srv://atlasuser:${MONGODB_PASSWORD}@cluster0.q0wpkss.mongodb.net/tacoclouddb
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true